- name: Python模块检查

  env:
    PYTHONPATH: ${{ github.workspace }}

  run: |

    echo "开始检查模块"

    python - <<'PY'

    import os
    import sys

    sys.path.insert(
        0,
        os.getcwd()
    )

    print("当前目录:")
    print(os.getcwd())

    print(sys.path)


    import config

    print("✅ config正常")


    from core.database import init_database

    print("✅ database正常")


    init_database()

    print("✅ 数据库初始化正常")

    PY
